# Generated by Django 2.2.3 on 2019-07-04 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
