# Generated by Django 2.2.3 on 2019-07-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('num', models.IntegerField()),
            ],
        ),
    ]
